/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedPostsRouteRouteImport } from './routes/_authed/posts.route'
import { Route as AuthedHabitsRouteRouteImport } from './routes/_authed/habits.route'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedHabitsIndexRouteImport } from './routes/_authed/habits.index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'
import { Route as AuthedHabitsCreateRouteImport } from './routes/_authed/habits.create'
import { Route as AuthedHabitsHabitIdEditRouteImport } from './routes/_authed/habits.$habitId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostsRouteRoute = AuthedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHabitsRouteRoute = AuthedHabitsRouteRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedHabitsIndexRoute = AuthedHabitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedHabitsRouteRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedHabitsCreateRoute = AuthedHabitsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedHabitsRouteRoute,
} as any)
const AuthedHabitsHabitIdEditRoute = AuthedHabitsHabitIdEditRouteImport.update({
  id: '/$habitId/edit',
  path: '/$habitId/edit',
  getParentRoute: () => AuthedHabitsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/habits': typeof AuthedHabitsRouteRouteWithChildren
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/habits/create': typeof AuthedHabitsCreateRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/habits/': typeof AuthedHabitsIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/habits/$habitId/edit': typeof AuthedHabitsHabitIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/habits/create': typeof AuthedHabitsCreateRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/habits': typeof AuthedHabitsIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/habits/$habitId/edit': typeof AuthedHabitsHabitIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/habits': typeof AuthedHabitsRouteRouteWithChildren
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/_authed/habits/create': typeof AuthedHabitsCreateRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/habits/': typeof AuthedHabitsIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/habits/$habitId/edit': typeof AuthedHabitsHabitIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/habits'
    | '/posts'
    | '/habits/create'
    | '/posts/$postId'
    | '/habits/'
    | '/posts/'
    | '/habits/$habitId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/habits/create'
    | '/posts/$postId'
    | '/habits'
    | '/posts'
    | '/habits/$habitId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/habits'
    | '/_authed/posts'
    | '/_authed/habits/create'
    | '/_authed/posts/$postId'
    | '/_authed/habits/'
    | '/_authed/posts/'
    | '/_authed/habits/$habitId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/habits': {
      id: '/_authed/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthedHabitsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/habits/': {
      id: '/_authed/habits/'
      path: '/'
      fullPath: '/habits/'
      preLoaderRoute: typeof AuthedHabitsIndexRouteImport
      parentRoute: typeof AuthedHabitsRouteRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/habits/create': {
      id: '/_authed/habits/create'
      path: '/create'
      fullPath: '/habits/create'
      preLoaderRoute: typeof AuthedHabitsCreateRouteImport
      parentRoute: typeof AuthedHabitsRouteRoute
    }
    '/_authed/habits/$habitId/edit': {
      id: '/_authed/habits/$habitId/edit'
      path: '/$habitId/edit'
      fullPath: '/habits/$habitId/edit'
      preLoaderRoute: typeof AuthedHabitsHabitIdEditRouteImport
      parentRoute: typeof AuthedHabitsRouteRoute
    }
  }
}

interface AuthedHabitsRouteRouteChildren {
  AuthedHabitsCreateRoute: typeof AuthedHabitsCreateRoute
  AuthedHabitsIndexRoute: typeof AuthedHabitsIndexRoute
  AuthedHabitsHabitIdEditRoute: typeof AuthedHabitsHabitIdEditRoute
}

const AuthedHabitsRouteRouteChildren: AuthedHabitsRouteRouteChildren = {
  AuthedHabitsCreateRoute: AuthedHabitsCreateRoute,
  AuthedHabitsIndexRoute: AuthedHabitsIndexRoute,
  AuthedHabitsHabitIdEditRoute: AuthedHabitsHabitIdEditRoute,
}

const AuthedHabitsRouteRouteWithChildren =
  AuthedHabitsRouteRoute._addFileChildren(AuthedHabitsRouteRouteChildren)

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedHabitsRouteRoute: typeof AuthedHabitsRouteRouteWithChildren
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHabitsRouteRoute: AuthedHabitsRouteRouteWithChildren,
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
